/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ProtoBuffers.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ProtoBuffers.pb-c.h"
void   pre_buff__init
                     (PreBuff         *message)
{
  static PreBuff init_value = PRE_BUFF__INIT;
  *message = init_value;
}
size_t pre_buff__get_packed_size
                     (const PreBuff *message)
{
  assert(message->base.descriptor == &pre_buff__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t pre_buff__pack
                     (const PreBuff *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &pre_buff__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t pre_buff__pack_to_buffer
                     (const PreBuff *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &pre_buff__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PreBuff *
       pre_buff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PreBuff *)
     protobuf_c_message_unpack (&pre_buff__descriptor,
                                allocator, len, data);
}
void   pre_buff__free_unpacked
                     (PreBuff *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &pre_buff__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   login_buff__init
                     (LoginBuff         *message)
{
  static LoginBuff init_value = LOGIN_BUFF__INIT;
  *message = init_value;
}
size_t login_buff__get_packed_size
                     (const LoginBuff *message)
{
  assert(message->base.descriptor == &login_buff__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t login_buff__pack
                     (const LoginBuff *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &login_buff__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t login_buff__pack_to_buffer
                     (const LoginBuff *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &login_buff__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
LoginBuff *
       login_buff__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (LoginBuff *)
     protobuf_c_message_unpack (&login_buff__descriptor,
                                allocator, len, data);
}
void   login_buff__free_unpacked
                     (LoginBuff *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &login_buff__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor pre_buff__field_descriptors[2] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PreBuff, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(PreBuff, size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned pre_buff__field_indices_by_name[] = {
  1,   /* field[1] = size */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange pre_buff__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor pre_buff__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PreBuff",
  "PreBuff",
  "PreBuff",
  "",
  sizeof(PreBuff),
  2,
  pre_buff__field_descriptors,
  pre_buff__field_indices_by_name,
  1,  pre_buff__number_ranges,
  (ProtobufCMessageInit) pre_buff__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor login_buff__field_descriptors[2] =
{
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(LoginBuff, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(LoginBuff, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned login_buff__field_indices_by_name[] = {
  0,   /* field[0] = type */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange login_buff__number_ranges[1 + 1] =
{
  { 3, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor login_buff__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "LoginBuff",
  "LoginBuff",
  "LoginBuff",
  "",
  sizeof(LoginBuff),
  2,
  login_buff__field_descriptors,
  login_buff__field_indices_by_name,
  1,  login_buff__number_ranges,
  (ProtobufCMessageInit) login_buff__init,
  NULL,NULL,NULL    /* reserved[123] */
};
