/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ProtoBuffers.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ProtoBuffers.pb-c.h"
void   message__init
                     (Message         *message)
{
  static Message init_value = MESSAGE__INIT;
  *message = init_value;
}
size_t message__get_packed_size
                     (const Message *message)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t message__pack
                     (const Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t message__pack_to_buffer
                     (const Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Message *
       message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Message *)
     protobuf_c_message_unpack (&message__descriptor,
                                allocator, len, data);
}
void   message__free_unpacked
                     (Message *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor message__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Message, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Message, username),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Message, chat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned message__field_indices_by_name[] = {
  2,   /* field[2] = chat */
  0,   /* field[0] = type */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Message",
  "Message",
  "Message",
  "",
  sizeof(Message),
  3,
  message__field_descriptors,
  message__field_indices_by_name,
  1,  message__number_ranges,
  (ProtobufCMessageInit) message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
